name: Build, run & test on Linux

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: sudo apt-get install clang-8 libqt5opengl5-dev libglvnd-dev libeigen3-dev zlib1g-dev libfftw3-dev
    - name: configure
      run: QT_SELECT=qt5 ./configure -assert
    - name: build
      run: ./build
    - name: test
      run: ./run_tests

